#%RAML 1.0
title: Customer 360 APIs
version: v1
baseUri: /api/v1

/accounts:
  get:
    description: Get all accounts
    responses:
      200:
        body:
          application/json:
            type: Account[]
            example:
              [
                {
                  "id": "001ABC",
                  "name": "Vibexo Tech"
                }
              ]

/accounts/{id}:
  get:
    description: Get account by Id
    responses:
      200:
        body:
          application/json:
            type: Account
            example: !include examples/account-example.json

types:
  Account: !include datatypes/Account.raml
