#%RAML 1.0
title: Customer 360 APIs
version: v1
baseUri: /api/v1

traits:
  client-id-required: !include traits/client-id-required.raml

types:
  Account: !include datatypes/Account.raml
  Contact: !include datatypes/Contact.raml
  Opportunity: !include datatypes/Opportunity.raml

/accounts:
  is:
    - client-id-required

  get:
    description: Get all accounts
    responses:
      200:
        body:
          application/json:
            type: Account[]

/accounts/{id}:
  is:
    - client-id-required

  get:
    description: Get account by Id
    responses:
      200:
        body:
          application/json:
            type: Account
            example: !include examples/account-example.json

/contacts:
  is:
    - client-id-required

  get:
    description: Get all contacts
    responses:
      200:
        body:
          application/json:
            type: Contact[]

/contacts/{id}:
  is:
    - client-id-required

  get:
    description: Get contact by Id
    responses:
      200:
        body:
          application/json:
            type: Contact
            example: !include examples/contact-example.json

/opportunities:
  is:
    - client-id-required

  get:
    description: Get all opportunities
    responses:
      200:
        body:
          application/json:
            type: Opportunity[]

/opportunities/{id}:
  is:
    - client-id-required

  get:
    description: Get opportunity by Id
    responses:
      200:
        body:
          application/json:
            type: Opportunity
            example: !include examples/opportunity-example.json
